fix for hibernate when no root is required and hibernatable swapfile is already configured

diff --git a/tree/usr/sbin/hibernate-from-file b/tree/usr/sbin/hibernate-from-file
--- a/tree/usr/sbin/hibernate-from-file
+++ b/tree/usr/sbin/hibernate-from-file
@@ -18,6 +18,14 @@
 set -o pipefail
 
 # ============================================================================
+#  ROOT CHECK
+# ============================================================================
+if [[ $EUID -ne 0 ]]; then
+    echo "Error: This script must be run as root." >&2
+    exit 1
+fi
+
+# ============================================================================
 #  CONSTANTS
 # ============================================================================
 readonly PROG="smart-hibernate"
